version: "3.1"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/services/frontend.Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root_password@db:3306/demo_budget_app
    volumes:
      - .:/app
      - ./services/frontend/node_modules:/app/services/frontend/node_modules
    command: bash -c "yarn workspace @services/frontend dev"
  backend:
    build:
      context: ./
      dockerfile: ./docker/services/backend.Dockerfile
      target: development
    ports:
      - "5000:3000"
    environment:
      DATABASE_URL: mysql://root:root_password@db:3306/demo_budget_app
    volumes:
      - .:/app
      - ./services/backend/node_modules:/app/services/backend/node_modules
    command: bash -c "yarn workspace @services/backend start"
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: demo_budget_app
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
