version: "3.1"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "3001:3000"
    volumes:
      - ./frontend/files/app:/app
    command: bash -c "npm install && npm run dev"
  backend:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5000"
    environment:
      MYSQL_DATABASE: demo_budget_app
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - ./backend/files/app:/app
    command: bash -c "flask run --host=0.0.0.0"
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: demo_budget_app
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
